Defining Event Class and implementing core methods + unittest and verbosity script
ECE444/Byte_Benevolence pull request #2
Opened 2023-10-22 17:05 UTC by HarryHuCodes

# Description 
Pull request for tasks from our first sprint and parts of week 2 deliverables

## Deliverable 1
1. Created event class with relevant data members and methods 
2. Applied encapsulation to some attributes and added accessor/mutator methods for them
3. Simulated method overloading using python's substitute ~*arg syntax~ by providing noneType to constructor parameters
4. Made 'event_sampleObj' showcasing a sample event object instantiation, its methods, and usage

## Deliverable 2 
1. Wrote unittest for verifying the functionality of event class and associated methods
2. Created script for running -v verbosity on event_unittest 

## Screenshots

![sampleObj event](https://github.com/ECE444/Byte_Benevolence/assets/48864969/9fba3259-8f27-4e70-b9e3-c6e44341e5f0)
![event_unittest](https://github.com/ECE444/Byte_Benevolence/assets/48864969/fe22777e-ad7f-4e5d-a516-366d4aeb799a)

2023-10-24 21:44 UTC, lucasnchoi requested changes
In general, looks good to me.  Should be good to merge once those pycaches are removed. My only other comment, I think it'd be nice to have all the files related to the event class in a separate folder to help with repo organization but if you want to wait until we have a better of how the models and db are going to work that's also fair.

2023-10-24 21:44 UTC, lucasnchoi commented on __pycache__/event_class.cpython-310.pyc
As I mentioned in the meeting, let's keep pycaches and other local environment files out of the repo. 
I added a gitignore file in #1 so you'll only have to remove it manually for this PR.

2023-10-24 21:44 UTC, lucasnchoi commented on __pycache__/event_unittest.cpython-310.pyc
same as above.

2023-10-24 21:44 UTC, lucasnchoi commented on event_class.py
Looks good!
The only thing I think might need to be added is some sort of organization ID field (if an event is created by/for an org. But I'll let you and Matt decide how you want to approach this.

2023-10-24 21:44 UTC, lucasnchoi commented on event_unittest.py
Unit tests look good!

2023-10-26 14:40 UTC, merged

2023-10-26 14:47 UTC, HarryHuCodes commented on __pycache__/event_class.cpython-310.pyc
Thanks, pycaches have been removed.

2023-10-26 14:50 UTC, HarryHuCodes commented on event_class.py
Will update once I confirm with Matt and go over the organization class.